name: projeto

services:

  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-projeto} 
      - POSTGRES_USER=${POSTGRES_USER:-projeto}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-projeto}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-projeto} -d ${POSTGRES_DB:-projeto}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  app:
    image: rafaelgp3/projetocloud-fastapi:v1
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-projeto} 
      - POSTGRES_USER=${POSTGRES_USER:-projeto}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-projeto}
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
        restart: true